backend:
  name: github
  repo: jocvegar/gridsome_blog

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Cover Image", name: "cover_image", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "CanonicalUrl", name: "canonical_url", widget: "boolean", default: false}
      - {label: "Description", name: "description", widget: "markdown"}
